start-at-login = true

after-login-command = []

after-startup-command = [
  'exec-and-forget borders active_color=0xCFEBBF83 inactive_color=0x33434c5e width=4.0',
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget /bin/bash -c sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = [{ monitor.'^built-in retina display' = 27 }, 56]
outer.right = 10

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-1 = 'workspace --auto-back-and-forth 1'  # Terminal
alt-2 = 'workspace --auto-back-and-forth 2'  # Browser
alt-3 = 'workspace --auto-back-and-forth 3'  # AltBrowser
alt-4 = 'workspace --auto-back-and-forth 4'  # Chat
alt-5 = 'workspace --auto-back-and-forth 5'  # Mail
alt-6 = 'workspace --auto-back-and-forth 6'  # Music
alt-7 = 'workspace --auto-back-and-forth 7'  # Secrets
alt-8 = 'workspace --auto-back-and-forth 8'  # Meeting
alt-9 = 'workspace --auto-back-and-forth 9'  # Notes
alt-0 = 'workspace --auto-back-and-forth 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-space = [
  'mode service',
  'exec-and-forget sketchybar --trigger send_message MESSAGE="SERVICE MODE" HOLD="true"',
]

[mode.service.binding]
esc = [
  'reload-config',
  'exec-and-forget sketchybar --trigger hide_message',
  'exec-and-forget sketchybar --reload',
  'mode main',
]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.microsoft.edgemac'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'
